version: "3.8"
services:
  db:
    image: mysql
    container_name: tasker_mysql_db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tasker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
