spring:
  application:
    name: calendar-manager
google:
  credentials:
    path: /credentials.json
server:
  port: 8092
auth:
  jwt:
    secret: Moj secret
queue-manager:
  url: http://localhost:8083/api/v1/queue