global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calendar-manager'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['calendar-manager:8092']

  - job_name: 'calendar-manager-entrance'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['calendar-manager-entrance:8088']

  - job_name: 'queue-manager'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['queue-manager:8083']