spring:
  application:
    name=queue-manager
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:tasker_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8083

queue:
  max-retries: 3
  repetition-time: 10000

auth:
  jwt:
    secret: Moj secret