spring:
  application:
    name=project-manager

  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:tasker_db}?useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082

auth:
  jwt:
    secret: Moj secret