name: Build and analyze all microservices with SpotBugs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build and analyze issue manager
      run: |
        cd issue-manager
        mvn clean verify org.jacoco:jacoco-maven-plugin:report org.apache.maven.plugins:maven-site-plugin:site -DgenerateReports=false
        mvn com.github.spotbugs:spotbugs-maven-plugin:check
        
    - name: Build and analyze manager
      run: |
        cd project-manager
        mvn clean verify org.jacoco:jacoco-maven-plugin:report org.apache.maven.plugins:maven-site-plugin:site -DgenerateReports=false
        mvn com.github.spotbugs:spotbugs-maven-plugin:check

    - name: Build and analyze queue manager
      run: |
        cd queue-manager
        mvn clean verify org.jacoco:jacoco-maven-plugin:report org.apache.maven.plugins:maven-site-plugin:site -DgenerateReports=false
        mvn com.github.spotbugs:spotbugs-maven-plugin:check
