name: Build all microservices

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build issue manager
      run: |
        cd issue-manager
        mvn clean install
        
    - name: Build project manager
      run: |
        cd project-manager
        mvn clean install

    - name: Build queue manager
      run: |
        cd queue-manager
        mvn clean install
